config/routes.rb
Rails.application.routes.draw do
  
  # devise_for :admins
  devise_for :users
  resources :posts do
  	resources :comments
  end
  namespace :admin do
    get '', to: 'dashboard#index'
    resources :users
  end

  root 'posts#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
	validates :title, presence: true
	validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
  		:registerable,
         :recoverable, 
         :rememberable, 
         :trackable, 
         :validatable
         validates :password, confirmation: true
         has_many :posts
         has_many :comments

         

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  
  
  def index
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_users_url, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: [:admin,@user] }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(params[:user].permit(:name, :address, :email))
      redirect_to admin_user_path
    else
      render 'edit'
    end
  end
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_path
  end
  private

  def user_params
    params.require(:user).permit(:name, :email, :address, :password)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
            devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :address, :date_of_birth) }
        end


  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :require_permission, only: :edit

	def new
		@comments = current_user.comments.build
	end
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comment_params)
		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end

	def show
		@comment = Comment.find(params[:id])
		@comment.user = current_user
	end
	def edit
		@comment = Comment.find(params[:id])
		@comment.user
	end

	def update
		@comment = Comment.find(params[:id])
		@comment.update	
	end
	def require_permission
		if current_user != Comment.find(params[:id]).user
		redirect_to root_path
		end	
	end

	private
    def comment_params
      params.require(:comment).permit(:body).merge(:user_id => current_user.id)
    end 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate, except: [:index, :show]

	def index
		@posts = Post.all.order('created_at DESC')
	end

	def new
		@post = current_user.posts.build
	end

	def create
		
		@post = current_user.posts.build(post_params)
		respond_to do |format|
			if @post.save
				format.html {redirect_to @post, notice: 'post was created'}
				format.json {render :show, status: :created, location: @post}
			else
				format.html {render :new}
				format.json {render json: @post.errors, status: :unprocessable_entity}
			end
		end
	end

	def show
		@post = Post.find(params[:id])
		@post.user
	end

	def edit
		@post = Post.find(params[:id])
		@post.user
	end	
	def update
		@post = Post.find(params[:id])
		if @post.update(params[:post].permit(:title, :body))
			redirect_to @post
		else
			render 'edit'
		end
	end
	def authenticate
		authenticate_user! && current_user.admin?
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to root_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	# def index
	# 	@posts = current_user.posts
	# end

	# def show
	# 	@user = User.find(params[:id])
	# end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/dashboard/index.html.erb
<h1>Administration</h1>

<ul>
  <li><%= link_to 'Manage Users', admin_users_path %></li>
</ul>

app/views/admin/users/_form.html.erb
<%= form_for @user, url: admin_user_path(@user), html: { method: :patch } do |f| %>
	
	<% if @user.errors.any? %>
		<div id="error">
			<p>You have <%= pluralize(@user.errors.count, "error") %> . Please check the list below and correct them.</p>
		</div>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		</ul>
		<% end %>
	<% end %>
		
	<table summary="user">
		<tr>
			<th><%= f.label :name, "Name" %></th>
			<td> <%= f.text_field :name, class: "text_field" %></td>
		</tr>
		<tr>
			<th><%= f.label :address, "Address" %></th>
			<td><%= f.text_area :address, class: "text_area" %></td>
		</tr>
		<tr>
			<th><%= f.label :email, "email" %></th>
			<td><%= f.text_area :email, class: "text_area" %></td>
		</tr>
	</table>	

		<%= f.submit "Submit", class: "submit", :disable_with => 'Submiting...' %>
	
<% end %> 

<%= link_to 'delete this user', admin_user_path, method: :delete, data: {confirm: 'are you sure you want to delete this user?'} %>

app/views/admin/users/edit.html.erb
<h3>Edit this user</h3>

<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to user.email, admin_user_path(user) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_admin_user_path %>

app/views/admin/users/show.html.erb
<h3 class="user">
	<%= @user.email %>
	<%= @user.name %>
	<%= @user.address %>

	<%= link_to 'edit this user', edit_admin_user_path(@user) %>
		<%= link_to 'delete this user', admin_user_path(@user), method: :delete, data: {confirm: 'are you sure you want to delete this user?'} %>
</h3>

app/views/comments/_comment.html.erb
<div class="comment">
	<div class="comment_content">
		
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> ago</p>
		
	</div>
	
	<% if comment.user == current_user %>
	<p><%= link_to 'delete', [comment.post, comment],
					method: :delete,
					class: "button",
					data: {confirm: 'Are you sure you want to delete this comment?'}%></p>
	<% end %>
	
</div>

app/views/comments/_form.html.erb
 <%= form_for([@post, @post.comments.build]) do |f| %>

 		
 		<p>
 			<%= f.label :body, "Comments" %>
 			<%= f.text_area :body, class: "text_area" %>
 		</p>
 		<%= f.submit "Submit", class: "submit", :disable_with => 'Submiting...' %>
		
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="header">	
	<% if user_signed_in? %>
		<p> Hello <%= current_user.name %></p>
		<%= link_to "New Post", new_post_path %>
		<%= link_to 'Log Out', destroy_user_session_path, method: :delete, data: {confirm: 'are you sure you want to sign out?'} %>
		<% else %>
			<%= link_to 'login', user_session_path %>
			<%= link_to 'signup', new_user_registration_path %>
	<% end %>
	<% flash.each do |name, msg| %>
	<%= content_tag(:div, msg, class: 'alert') %>
	<% end %>
</div>



<div id="container1">


	<div class="col1">
		<ul>
			<li class="category">Website</li>
			<li><%= link_to 'blog', root_path %></li>
			<li>About</li>
		</ul>

	</div>

	<div class="col2">
	
		<%= yield %>
	</div>

	<div class="col3">
		
		"column 3 goes here"
	</div>

</div>



<footer>This is the footer</footer>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	
	<% if @post.errors.any? %>
		<div id="error">
			<p>You have <%= pluralize(@post.errors.count, "error") %> . Please check the list below and correct them.</p>
		</div>
		<ul>
			<% @post.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		</ul>
		<% end %>
	<% end %>
		
	<table summary="posts">
		<tr>
			<th><%= f.label :title, "Title" %></th>
			<td> <%= f.text_field :title, class: "text_field" %></td>
		</tr>
		<tr>
			<th><%= f.label :body, "Post" %></th>
			<td><%= f.text_area :body, class: "text_area" %></td>
		</tr>
	</table>	

		<%= f.submit "Submit", class: "submit", :disable_with => 'Submiting...' %>

		
<% end %> 

app/views/posts/edit.html.erb
<h2>Edit this post</h2>

<%= render 'form' %>

app/views/posts/index.html.erb
<h2>Posts</h2>

<% @posts.each do |post| %>
	<div class="post_wrapper">
		<h2 class="title">
			<%= link_to post.title, post %>
		</h2>
		<p class="date">
			<p>Post created on	<%= post.created_at.strftime('%B, %d, %Y') %> by <%= post.user.name %> </p>
			</p>
	</div>
	
<% end %>

app/views/posts/new.html.erb
<h2>New Post</h2>

 <%= render 'form' %>

app/views/posts/show.html.erb
<h3 class="title">
	<%= @post.title %>
</h3>

<p class="date">
	Submitted <%= time_ago_in_words(@post.created_at) %> ago<br> 
	<% if @post.user == current_user %>
		<%= link_to 'edit this post', edit_post_path(@post) %>
		<%= link_to 'delete this post', post_path(@post), method: :delete, data: {confirm: 'are you sure you want to delete this post?'} %>
		
	<% end %>
	<!-- <svg height="10" width="2000">
  <line x1="0" y1="5" x2="1000" y2="5" style="stroke:rgb(0,0,0);stroke-width:1" />
  Sorry, your browser does not support inline SVG.
</svg> -->
</p>

<p class="body">
	
	<%= @post.body %>
</p>

<div id="comments">
	<%= @post.comments.count %> comments
	<%= render @post.comments %>

	<p>Add a comment</p>
	<%= render 'comments/form' %>

</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>